spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/bbk/mapper/*.xml
  type-aliases-package: com.bbk.entity